// Bilingual content for Mẫu Chi Uyên
window.CONTENT = {
  nav: {
    vi: [
      { id: "about", label: "Giới thiệu" },
      { id: "programs", label: "Chương trình" },
      { id: "events", label: "Sự kiện" },
      { id: "stories", label: "Câu chuyện" },
      { id: "resources", label: "Tài liệu" },
      { id: "news", label: "Tin tức" },
      { id: "contact", label: "Liên hệ" },
    ],
    zh: [
      { id: "about", label: "關於我們" },
      { id: "programs", label: "服務項目" },
      { id: "events", label: "活動" },
      { id: "stories", label: "媽媽的故事" },
      { id: "resources", label: "資源" },
      { id: "news", label: "最新消息" },
      { id: "contact", label: "聯絡我們" },
    ],
  },

  hero: {
    vi: {
      eyebrow: "một không gian nhỏ cho mẹ Việt",
      title: "Ở đây,",
      titleEm: "bạn không một mình.",
      tcTitle: "母之苑 ·\n越南媽媽育兒心驛站",
      lede: "Mẫu Chi Uyên là không gian kết nối và sẻ chia cho các mẹ Việt đang mang thai và nuôi con nhỏ tại Đài Loan — nơi thông tin y tế, thủ tục và kinh nghiệm được dịch thành tiếng Việt dễ hiểu, và nơi không một câu hỏi nào là quá nhỏ.",
      cta1: "Tham gia cộng đồng",
      cta2: "Đọc câu chuyện của chúng tôi",
      sealSub: "một nơi để về",
      sproutText: "Dìu Mẹ Đón Con · 2026",
    },
    zh: {
      eyebrow: "給越南媽媽的一方小天地",
      title: "在這裡，",
      titleEm: "你不是一個人。",
      tcTitle: "Mẫu Chi Uyên · Vietnamese Mothers in Taiwan",
      lede: "母之苑是為在台灣懷孕及育兒的越南媽媽建立的連結與分享空間——這裡將醫療資訊、行政流程與經驗翻譯成易懂的越南語，任何問題都不嫌小。",
      cta1: "加入社群",
      cta2: "我們的故事",
      sealSub: "一個可以回去的地方",
      sproutText: "陪媽媽迎接寶寶 · 2026",
    },
  },

  letter: {
    vi: {
      kicker: "Lời ngỏ từ người sáng lập",
      stampTc: "母",
      stampSub: "mother",
      creditSmall: "viết bởi",
      creditName: "Chi Uyên",
      creditRole: "người sáng lập · Đài Bắc, mùa xuân 2026",
      paras: [
        { type: "p", drop: true, text: "Nếu bạn đang đọc những dòng này, có thể bạn là một mẹ Việt đang mang thai ở Đài Loan, một mẹ đang nuôi con nhỏ, hoặc đơn giản là một người đang tìm hiểu về hành trình làm mẹ xa xứ." },
        { type: "p", text: "Mình tạo Mẫu Chi Uyên từ một trải nghiệm rất cá nhân. Mặc dù đã học tập và sinh sống gần 5 năm tại Đài Loan, khi mang thai, mỗi lần đi khám thai mình vẫn cảm thấy rất lo lắng và hoang mang." },
        { type: "quote", text: "Ủa… bác sĩ nói lúc nãy là gì vậy ta?" },
        { type: "p", text: "Không phải vì bác sĩ nói không rõ, mà vì những thuật ngữ y khoa bằng tiếng Trung đôi khi thật sự rất khó hiểu. Về nhà mình cố gắng tìm lại thông tin, nhưng lại không nhớ chính xác từ bác sĩ đã nói. Hỏi bạn bè thì mỗi người chia sẻ một cách khác nhau. Càng tìm, mình càng thấy rối." },
        { type: "p", text: "Nhiều lúc mình chỉ ước rằng giá mà có một nơi nào đó giải thích những điều này thật đơn giản bằng tiếng Việt. Và rồi mình tự hỏi — liệu có những mẹ Việt xa quê khác cũng đang trải qua cảm giác giống mình không?" },
        { type: "h", text: "Mẫu Chi Uyên là một không gian nhỏ để:" },
        { type: "ul", items: [
          "chia sẻ thông tin về thai sản và chăm sóc em bé tại Đài Loan",
          "giải thích các trợ cấp, thủ tục và dịch vụ y tế bằng tiếng Việt dễ hiểu",
          "chia sẻ kinh nghiệm thật từ các mẹ Việt",
          "và quan trọng nhất — để các mẹ biết rằng mình không phải một mình ở đây",
        ]},
        { type: "p", text: "Ở đây không cần hoàn hảo, chỉ cần chân thành và tử tế với nhau." },
      ],
    },
    zh: {
      kicker: "創辦人的話",
      stampTc: "母",
      stampSub: "mother",
      creditSmall: "撰文",
      creditName: "Chi Uyên",
      creditRole: "創辦人 · 台北，2026 春",
      paras: [
        { type: "p", drop: true, text: "如果你正在讀這些文字，你可能是一位在台灣懷孕的越南媽媽、一位正在育兒的媽媽，或只是想了解遠離家鄉的母親旅程的人。" },
        { type: "p", text: "母之苑源自一個非常個人的經驗。雖然我在台灣求學、生活將近五年，但懷孕後每次產檢，我仍然感到非常焦慮與困惑。" },
        { type: "quote", text: "欸⋯⋯醫生剛剛到底說了什麼？" },
        { type: "p", text: "不是醫生講得不清楚，而是中文醫療術語有時真的很難懂。回家後想再查資料，卻又記不清楚醫生說了什麼。問朋友，每個人的說法又不一樣。越查越亂。" },
        { type: "p", text: "很多時候我只是希望——如果有一個地方能用簡單的越南語解釋這些事情，該有多好。於是我問自己，是不是也有其他遠離家鄉的越南媽媽，和我一樣感到不安？" },
        { type: "h", text: "母之苑是一個小小的空間，我們:" },
        { type: "ul", items: [
          "分享在台灣的懷孕與育兒資訊",
          "用易懂的越南語解釋補助、行政流程與醫療服務",
          "分享越南媽媽的真實經驗",
          "最重要的——讓媽媽們知道，自己在這裡並不孤單",
        ]},
        { type: "p", text: "這裡不需要完美，只需要真誠與善意。" },
      ],
    },
  },

  programs: {
    vi: {
      kicker: "Những gì chúng mình làm",
      title: "Chương trình",
      tcTitle: "我們的服務項目",
      intro: "Bốn mảng hoạt động chính — xoay quanh hành trình làm mẹ từ khi mang thai đến khi em bé đủ lớn để đến trường.",
      items: [
        { num: "01", title: "Dìu Mẹ Đón Con", sub: "陪媽媽迎接寶寶", pill: "Dự án chính · 2026", desc: "Chương trình đồng hành với mẹ Việt từ khi mang thai đến sau sinh. Bao gồm các buổi trò chuyện với bác sĩ Việt–Hoa, nhóm hỗ trợ, và tài liệu song ngữ.", featured: true, href: "handbook.html", linkLabel: "Xem sổ tay →" },
        { num: "02", title: "Dịch thuật y tế", sub: "醫療翻譯", pill: "Hàng tuần", desc: "Giải thích các thuật ngữ sản khoa, nhi khoa và kết quả xét nghiệm bằng tiếng Việt đơn giản, dễ hiểu." },
        { num: "03", title: "Nhóm mẹ & bé", sub: "媽媽寶寶聚會", pill: "Hàng tháng · Đài Bắc", desc: "Gặp mặt trực tiếp cho mẹ và em bé. Chia sẻ, chơi cùng nhau, và xây dựng tình bạn xa quê." },
        { num: "04", title: "Hỗ trợ thủ tục", sub: "行政協助", pill: "Theo yêu cầu", desc: "Hướng dẫn đăng ký bảo hiểm y tế, trợ cấp sinh con, thẻ cư trú cho em bé và các thủ tục hành chính khác." },
        { num: "05", title: "Podcast kể chuyện", sub: "媽媽的聲音", pill: "Ra mắt tháng 5", desc: "Những câu chuyện thật từ các mẹ Việt — làm mẹ ở Đài Loan trông như thế nào, bằng chính giọng nói của họ." },
        { num: "06", title: "Thư viện song ngữ", sub: "雙語資源庫", pill: "Luôn mở", desc: "Tài liệu, bài viết và video về mang thai, sinh nở, nuôi con — được biên dịch và kiểm tra bởi chuyên gia." },
      ],
    },
    zh: {
      kicker: "我們在做的事",
      title: "服務項目",
      tcTitle: "Chương trình",
      intro: "我們的工作分為六大類——圍繞著媽媽的旅程，從懷孕、生產，到孩子上學之前。",
      items: [
        { num: "01", title: "陪媽媽迎接寶寶", sub: "Dìu Mẹ Đón Con", pill: "旗艦計畫 · 2026", desc: "從懷孕到產後全程陪伴越南媽媽的計畫。包含中越雙語醫師座談、支持團體，以及雙語衛教資料。", featured: true, href: "handbook.html", linkLabel: "查看手冊 →" },
        { num: "02", title: "醫療翻譯", sub: "Dịch thuật y tế", pill: "每週", desc: "以簡單易懂的越南語解釋產科、兒科術語與檢查報告。" },
        { num: "03", title: "媽媽寶寶聚會", sub: "Nhóm mẹ & bé", pill: "每月 · 台北", desc: "媽媽與寶寶的實體聚會。一起分享、遊戲，在異鄉建立友誼。" },
        { num: "04", title: "行政協助", sub: "Hỗ trợ thủ tục", pill: "依需求", desc: "協助健保登記、生育津貼、寶寶居留證等各項行政手續。" },
        { num: "05", title: "媽媽的聲音 Podcast", sub: "Podcast kể chuyện", pill: "5 月推出", desc: "越南媽媽的真實故事——用她們自己的聲音，訴說在台灣當媽媽是什麼樣子。" },
        { num: "06", title: "雙語資源庫", sub: "Thư viện song ngữ", pill: "長期開放", desc: "關於懷孕、生產、育兒的文章與影片——由專業人員翻譯並審閱。" },
      ],
    },
  },

  events: {
    vi: {
      kicker: "Lịch sắp tới",
      title: "Sự kiện & đăng ký",
      tcTitle: "活動資訊",
      intro: "Các buổi gặp mặt, hội thảo và nhóm hỗ trợ. Đăng ký miễn phí — nếu lịch không tiện, bạn có thể yêu cầu ghi âm để nghe lại sau.",
      items: [
        { day: "24", mo: "Th.4", title: "Hiểu kết quả siêu âm thai", titleZh: "認識產檢超音波報告", location: "Đài Bắc · Zhongshan", meta: ["14:00–16:00", "BS. Lê Ngọc Anh", "Song ngữ"], status: "open", id: "evt-01" },
        { day: "08", mo: "Th.5", title: "Nhóm mẹ bầu cuối thai kỳ", titleZh: "孕晚期媽媽支持團體", location: "Đài Bắc · NIA", meta: ["10:00–12:00", "Offline", "10 chỗ"], status: "registered", id: "evt-02" },
        { day: "15", mo: "Th.5", title: "Thủ tục sinh con & bảo hiểm y tế", titleZh: "生產手續與健保申請", location: "Online · Zoom", meta: ["19:30–21:00", "LS. Nguyễn Minh", "Tiếng Việt"], status: "full", id: "evt-03" },
        { day: "29", mo: "Th.5", title: "Cho con bú & dinh dưỡng mẹ", titleZh: "哺乳與產後營養", location: "Đài Bắc · NIA", meta: ["14:00–16:30", "BS. Trần Thảo", "Song ngữ"], status: "open", id: "evt-04" },
        { day: "12", mo: "Th.6", title: "Ngày hội mẹ & bé Việt Nam", titleZh: "越南媽媽寶寶聚會", location: "Công viên Đại An", meta: ["Cả ngày", "Mang theo bé", "Miễn phí"], status: "open", id: "evt-05" },
        { day: "26", mo: "Th.6", title: "Kể chuyện bằng tiếng Việt", titleZh: "越南語親子共讀", location: "Thư viện Đài Bắc", meta: ["10:00–11:00", "Gia đình", "Miễn phí"], status: "open", id: "evt-06" },
      ],
    },
    zh: {
      kicker: "即將舉辦",
      title: "活動與報名",
      tcTitle: "Sự kiện & đăng ký",
      intro: "聚會、工作坊與支持團體。報名免費——若時間不合，可索取錄音檔。",
      items: [
        { day: "24", mo: "4月", title: "認識產檢超音波報告", titleZh: "Hiểu kết quả siêu âm thai", location: "台北 · 中山區", meta: ["14:00–16:00", "黎玉英醫師", "中越雙語"], status: "open", id: "evt-01" },
        { day: "08", mo: "5月", title: "孕晚期媽媽支持團體", titleZh: "Nhóm mẹ bầu cuối thai kỳ", location: "台北 · 移民署", meta: ["10:00–12:00", "實體", "限 10 位"], status: "registered", id: "evt-02" },
        { day: "15", mo: "5月", title: "生產手續與健保申請", titleZh: "Thủ tục sinh con & bảo hiểm y tế", location: "線上 · Zoom", meta: ["19:30–21:00", "阮明律師", "越南語"], status: "full", id: "evt-03" },
        { day: "29", mo: "5月", title: "哺乳與產後營養", titleZh: "Cho con bú & dinh dưỡng mẹ", location: "台北 · 移民署", meta: ["14:00–16:30", "陳草醫師", "中越雙語"], status: "open", id: "evt-04" },
        { day: "12", mo: "6月", title: "越南媽媽寶寶聚會", titleZh: "Ngày hội mẹ & bé Việt Nam", location: "大安森林公園", meta: ["整日", "攜伴寶寶", "免費"], status: "open", id: "evt-05" },
        { day: "26", mo: "6月", title: "越南語親子共讀", titleZh: "Kể chuyện bằng tiếng Việt", location: "台北市立圖書館", meta: ["10:00–11:00", "親子", "免費"], status: "open", id: "evt-06" },
      ],
    },
  },

  stories: {
    vi: {
      kicker: "Giọng nói từ cộng đồng",
      title: "Câu chuyện của các mẹ",
      tcTitle: "媽媽的故事",
      intro: "Những chia sẻ thật, bằng chính lời của các mẹ đã đi qua hành trình này trước chúng ta.",
      items: [
        { quote: "Lần đầu nghe bác sĩ nói 'nhau tiền đạo', mình khóc cả đêm vì không biết có nghiêm trọng không. Nếu lúc đó có Mẫu Chi Uyên, mình đã không phải một mình như vậy.", name: "Hương", role: "mẹ của bé Linh · Tân Trúc", initial: "H", lead: true },
        { quote: "Đi họp nhóm mẹ ở Đài Bắc, lần đầu mình được nói tiếng Việt cả buổi. Cảm giác như về nhà.", name: "Thu", role: "mẹ của bé Duy", initial: "T" },
        { quote: "Nhờ bài viết về trợ cấp sinh con mà mình đăng ký kịp hạn. Cảm ơn các chị rất nhiều.", name: "Phượng", role: "Đài Trung", initial: "P" },
      ],
    },
    zh: {
      kicker: "社群的聲音",
      title: "媽媽們的故事",
      tcTitle: "Câu chuyện của các mẹ",
      intro: "真實的分享，由走過這段旅程的媽媽們親自訴說。",
      items: [
        { quote: "第一次聽到醫生說「前置胎盤」，我哭了一整晚，不知道嚴不嚴重。如果那時有母之苑，我就不會這麼孤單。", name: "Hương", role: "Linh 的媽媽 · 新竹", initial: "H", lead: true },
        { quote: "去台北的媽媽聚會，第一次整個下午都在講越南語，感覺像回家一樣。", name: "Thu", role: "Duy 的媽媽", initial: "T" },
        { quote: "多虧生育津貼的文章，我才及時申請到。真的非常感謝姐姐們。", name: "Phượng", role: "台中", initial: "P" },
      ],
    },
  },

  resources: {
    vi: {
      kicker: "Thư viện cộng đồng",
      title: "Tài liệu & hướng dẫn",
      tcTitle: "資源中心",
      intro: "Bộ sưu tập đang tăng dần — mỗi tài liệu được biên dịch và kiểm tra bởi chuyên gia hoặc bác sĩ người Việt sống tại Đài Loan.",
      filters: [
        { id: "all", label: "Tất cả" },
        { id: "health", label: "Y tế" },
        { id: "legal", label: "Pháp lý" },
        { id: "language", label: "Ngôn ngữ" },
        { id: "parenting", label: "Nuôi con" },
      ],
      langs: { vi: "Tiếng Việt", bi: "Song ngữ", zh: "中文" },
      items: [
        { cat: "health", icon: "医", title: "Sổ tay khám thai 0–40 tuần", titleZh: "產檢手冊 0–40 週", desc: "Giải thích từng buổi khám, các xét nghiệm và ý nghĩa của chúng.", lang: "bi" },
        { cat: "health", icon: "养", title: "Dinh dưỡng thai kỳ theo từng tam cá nguyệt", titleZh: "孕期各階段營養指南", desc: "Thực phẩm nên ăn, nên tránh, và món Việt phù hợp.", lang: "vi" },
        { cat: "legal", icon: "法", title: "Đăng ký bảo hiểm y tế cho em bé", titleZh: "新生兒健保登記指南", desc: "Hướng dẫn từng bước, kèm mẫu đơn và địa chỉ NIA.", lang: "bi" },
        { cat: "legal", icon: "签", title: "Thủ tục thẻ cư trú cho con", titleZh: "新生兒居留證申請", desc: "Giấy tờ cần chuẩn bị, thời gian xử lý, phí.", lang: "bi" },
        { cat: "language", icon: "语", title: "Từ điển thuật ngữ sản khoa", titleZh: "產科術語詞典", desc: "200+ thuật ngữ y khoa tiếng Trung thường gặp, phiên âm và nghĩa tiếng Việt.", lang: "bi" },
        { cat: "language", icon: "听", title: "Nghe hiểu khi đi khám", titleZh: "看診聽力練習", desc: "Audio các tình huống khám thai mẫu, có phụ đề song ngữ.", lang: "bi" },
        { cat: "parenting", icon: "育", title: "Giữ tiếng Việt cho con lớn lên ở Đài Loan", titleZh: "在台寶寶的越南語養成", desc: "Kinh nghiệm từ các mẹ — sách, bài hát, thói quen hàng ngày.", lang: "vi" },
        { cat: "parenting", icon: "睡", title: "Giấc ngủ & lịch ăn của em bé 0–12 tháng", titleZh: "0–12 個月寶寶作息表", desc: "Bảng tham khảo kèm lời khuyên từ bác sĩ nhi khoa.", lang: "bi" },
      ],
    },
    zh: {
      kicker: "社群資源庫",
      title: "資源與指南",
      tcTitle: "Tài liệu & hướng dẫn",
      intro: "持續成長的資源庫——每一份都經由在台越南籍專業人士或醫師翻譯與審閱。",
      filters: [
        { id: "all", label: "全部" },
        { id: "health", label: "醫療" },
        { id: "legal", label: "行政" },
        { id: "language", label: "語言" },
        { id: "parenting", label: "育兒" },
      ],
      langs: { vi: "越南語", bi: "雙語", zh: "中文" },
      items: [
        { cat: "health", icon: "医", title: "產檢手冊 0–40 週", titleZh: "Sổ tay khám thai 0–40 tuần", desc: "逐次產檢解說、檢查項目與意義。", lang: "bi" },
        { cat: "health", icon: "养", title: "孕期各階段營養指南", titleZh: "Dinh dưỡng thai kỳ", desc: "該吃什麼、該避免什麼,以及合適的越南料理。", lang: "vi" },
        { cat: "legal", icon: "法", title: "新生兒健保登記指南", titleZh: "Đăng ký bảo hiểm y tế cho em bé", desc: "逐步說明,附表格範例與移民署地址。", lang: "bi" },
        { cat: "legal", icon: "签", title: "新生兒居留證申請", titleZh: "Thủ tục thẻ cư trú", desc: "所需文件、辦理時程、規費。", lang: "bi" },
        { cat: "language", icon: "语", title: "產科術語詞典", titleZh: "Từ điển thuật ngữ sản khoa", desc: "200+ 常見中文醫療術語,附音譯與越南語翻譯。", lang: "bi" },
        { cat: "language", icon: "听", title: "看診聽力練習", titleZh: "Nghe hiểu khi đi khám", desc: "產檢情境音檔,含中越雙語字幕。", lang: "bi" },
        { cat: "parenting", icon: "育", title: "在台寶寶的越南語養成", titleZh: "Giữ tiếng Việt", desc: "媽媽們的經驗——書籍、歌曲、日常習慣。", lang: "vi" },
        { cat: "parenting", icon: "睡", title: "0–12 個月寶寶作息表", titleZh: "Giấc ngủ & lịch ăn", desc: "參考對照表,附兒科醫師建議。", lang: "bi" },
      ],
    },
  },

  news: {
    vi: {
      kicker: "Cập nhật mới",
      title: "Tin tức & nhật ký",
      tcTitle: "最新消息",
      intro: "Những gì đang diễn ra trong cộng đồng, trên mạng xã hội, và trong chương trình Dìu Mẹ Đón Con.",
      items: [
        { date: "12.04.2026", title: "Khởi động chương trình Dìu Mẹ Đón Con", titleZh: "「陪媽媽迎接寶寶」計畫正式啟動", excerpt: "Lễ khai mạc với sự có mặt của đại diện Cục Di Dân và 40 mẹ Việt từ khắp Đài Loan.", thumb: "thumb-1", label: "khởi động · taipei" },
        { date: "28.03.2026", title: "Phát hành 50 từ vựng y tế đầu tiên", titleZh: "首批 50 組醫療詞彙上線", excerpt: "Bộ từ vựng được biên dịch bởi BS. Lê Ngọc Anh và đội ngũ tình nguyện viên, đang có mặt miễn phí trên thư viện.", thumb: "thumb-2", label: "resource · v1" },
        { date: "14.03.2026", title: "Phỏng vấn trên Đài truyền hình dân tộc", titleZh: "原住民族電視台專訪", excerpt: "Chi Uyên chia sẻ về hành trình làm mẹ và lý do khởi xướng Mẫu Chi Uyên trong chương trình 'Người mới ở Đài Loan'.", thumb: "thumb-3", label: "media · TITV" },
      ],
    },
    zh: {
      kicker: "最新更新",
      title: "新聞與日誌",
      tcTitle: "Tin tức & nhật ký",
      intro: "社群、社交媒體以及「陪媽媽迎接寶寶」計畫的最新動態。",
      items: [
        { date: "2026.04.12", title: "「陪媽媽迎接寶寶」計畫正式啟動", titleZh: "Khởi động chương trình", excerpt: "啟動典禮由移民署代表出席,並邀來自全台 40 位越南媽媽共襄盛舉。", thumb: "thumb-1", label: "起跑 · 台北" },
        { date: "2026.03.28", title: "首批 50 組醫療詞彙上線", titleZh: "Phát hành từ vựng y tế", excerpt: "由黎玉英醫師與志工團隊翻譯完成,已在資源庫免費開放。", thumb: "thumb-2", label: "資源 · v1" },
        { date: "2026.03.14", title: "原住民族電視台專訪", titleZh: "Phỏng vấn truyền hình", excerpt: "Chi Uyên 於《台灣新來的人》節目中,分享她作為母親的旅程,以及創立母之苑的初衷。", thumb: "thumb-3", label: "媒體 · TITV" },
      ],
    },
  },

  contact: {
    vi: {
      title: "Chào bạn,",
      titleEm: "ghé sang chơi nhé?",
      lede: "Dù bạn là mẹ Việt cần hỗ trợ, tình nguyện viên muốn tham gia, hay đối tác muốn đồng hành — chúng mình đều muốn nghe từ bạn.",
      channels: [
        { icon: "f", title: "Cộng đồng Facebook", sub: "Mẫu Chi Uyên · 1,240 thành viên", href: "#" },
        { icon: "@", title: "hello@mauchiuyen.tw", sub: "Trả lời trong 24–48 giờ", href: "#" },
        { icon: "♥", title: "Group mẹ Việt", sub: "Tham gia group kín, được duyệt", href: "#" },
      ],
      formTitle: "Gửi chúng mình lời nhắn",
      formSub: "bất cứ điều gì trong lòng bạn",
      f_name: "Tên của bạn", f_name_ph: "Chi Uyên",
      f_email: "Email hoặc điện thoại", f_email_ph: "hello@example.com",
      f_topic: "Bạn muốn trao đổi về?",
      f_topic_opts: ["Tham gia cộng đồng", "Đăng ký sự kiện", "Đóng góp tài liệu", "Hợp tác / đối tác", "Báo chí", "Khác"],
      f_msg: "Lời nhắn", f_msg_ph: "Bạn có thể viết bằng tiếng Việt, tiếng Trung hoặc tiếng Anh.",
      f_submit: "Gửi lời nhắn",
      f_success_title: "Cảm ơn bạn đã viết cho chúng mình.",
      f_success: "Chúng mình sẽ trả lời trong 24–48 giờ. Chúc bạn và gia đình một ngày bình an.",
    },
    zh: {
      title: "哈囉，",
      titleEm: "要不要過來坐坐？",
      lede: "無論你是需要支援的越南媽媽、想加入的志工,或想合作的夥伴——我們都想聽聽你的故事。",
      channels: [
        { icon: "f", title: "Facebook 社群", sub: "母之苑 · 1,240 位成員", href: "#" },
        { icon: "@", title: "hello@mauchiuyen.tw", sub: "24–48 小時內回覆", href: "#" },
        { icon: "♥", title: "越南媽媽私密社團", sub: "申請加入,需審核", href: "#" },
      ],
      formTitle: "傳訊息給我們",
      formSub: "任何想說的都可以",
      f_name: "你的名字", f_name_ph: "Chi Uyên",
      f_email: "Email 或電話", f_email_ph: "hello@example.com",
      f_topic: "想聊什麼?",
      f_topic_opts: ["加入社群", "報名活動", "貢獻資源", "合作邀請", "媒體採訪", "其他"],
      f_msg: "訊息", f_msg_ph: "可以用越南語、中文或英文書寫。",
      f_submit: "送出訊息",
      f_success_title: "謝謝你寫信來。",
      f_success: "我們會在 24–48 小時內回覆。祝你和家人平安。",
    },
  },

  footer: {
    vi: {
      about: "Mẫu Chi Uyên là không gian kết nối cho các mẹ Việt tại Đài Loan. Dự án được hỗ trợ bởi Cục Di Dân Đài Loan.",
      col1: "Khám phá",
      col1_links: ["Giới thiệu", "Chương trình", "Sự kiện", "Câu chuyện"],
      col2: "Hỗ trợ",
      col2_links: ["Tài liệu", "Thủ tục y tế", "Thủ tục pháp lý", "Liên hệ"],
      col3: "Theo dõi",
      col3_links: ["Facebook", "Instagram", "Podcast", "Newsletter"],
      badge: "Tài trợ bởi",
      badgeOrg: "移民署 · 新住民及子女築夢計畫 (kỳ 12)",
      copy: "© 2026 Mẫu Chi Uyên · Dự án phi lợi nhuận · Đài Bắc, Đài Loan",
    },
    zh: {
      about: "母之苑是為在台灣的越南媽媽而設的連結空間。本計畫由中華民國內政部移民署補助。",
      col1: "探索",
      col1_links: ["關於我們", "服務項目", "活動", "媽媽的故事"],
      col2: "支援",
      col2_links: ["資源", "醫療", "行政", "聯絡"],
      col3: "追蹤我們",
      col3_links: ["Facebook", "Instagram", "Podcast", "電子報"],
      badge: "贊助單位",
      badgeOrg: "移民署 · 新住民及子女築夢計畫 (第 12 期)",
      copy: "© 2026 母之苑 · 非營利計畫 · 台灣台北",
    },
  },
};
